# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bxLEGfGbco-Cyyeq5lYdKeOAsuPrCJf-
"""

#Five functions of string

#Function No.1
lower_case='aravind'
Upper_case=name.upper()
print(Name)

#Function No.2
name='aravind'
value=name.count('a')
print('Number of times letter a is present in the name is', value)

#Function No.3
words=('Let','upgrade')
brand=('s'.join(words))
print(brand)

#Function No.4
colour='I like pink colour'
myfavourite=colour.replace('pink','Blue & Red')
print(myfavourite)

#Function No.5
language='I love python'
sentence=language.endswith('Java')
print(sentence)

#Five functions of list

#Function No.1
colour=['Red','Blue','Black','Green','White']
colour.append('orange')
print(colour)

#Function No.2
number=[2,5,2,9,79,5,9,461,9,1,23,5,8,3,6,5,6,5,5,5,]
count=number.count(9)
print(count)

#Function No.3
number=[2,5,2,9,79,5,9,461,9,1,23,5,8,3,6,5,6,5,5,5,]
number.remove(5)
print(number)

#Function No.4
number=[1,3,4,5]
number.insert(2,1)
print(number)

#Function No.5
colour=['Red','Blue','Black','Green','White']
colour.pop(1)
print(colour)

#Five functions of Dictionary

#Function No.1
car={1:'bmw',2:'tata'}
car.clear()
print(car)

#Function No.2
car={1:'bmw',2:'tata'}
find=car.get(2)
print(find)

#Function No.3
car={1:'bmw',2:'tata'}
remove=car.pop(1)
print(remove)

#Function No.4
car={1:'bmw',2:'tata'}
print(car.items())

#Function No.5
car={1:'bmw',2:'tata'}
car.update({3:'benz'})
print(car)