# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1peS8J0IBdzE-ynSyZEBVunKpG4qBZYZN
"""

#Question 1

subject1=22
subject2=80
subject3=95

if subject1>30:
  print('passed in subject1')
elif 30>subject1<50:
  print('Just passed in subject2')
else:
  print('superb')


#Question 2
for num in range(0,1001):  
   if num > 1:  
       for i in range(2,num):  
           if (num % i) == 0:  
               break  
       else:  
           print(num)

#Question 3
for i in range(1,13):
  for j in range(1,11):
     print(i, 'x', j, '=', i*j)

#Question 4
import sympy
x = int(input("Enter the number:"))
count = 0
n=3
while count < x:
  while n>2:
    result=sympy.isprime(n)
    if result == 1:
      print(n)
      count=count+1
    if count < x:
      n=n+1
    else:
      break